# Generated by Django 3.2.8 on 2021-11-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile_phone',
            field=models.CharField(default='', max_length=10, verbose_name='Mobile Phone Number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_phone',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Work Phone Number'),
        ),
    ]
