# Generated by Django 3.2.8 on 2021-10-25 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_name', models.CharField(default='', max_length=30, verbose_name='Title')),
                ('description', models.CharField(default='', max_length=200)),
                ('skillset_required', models.CharField(default='', max_length=200, verbose_name='Skillset Required')),
                ('severity_level', models.CharField(default='', max_length=20, verbose_name='Severity')),
                ('current_status', models.CharField(default='', max_length=25, verbose_name='Current Status')),
                ('desired_completion_date', models.DateTimeField(blank=True, verbose_name='Desired Completion Date')),
                ('actual_completion_date', models.DateTimeField(blank=True, verbose_name='Actual Completion Date')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default='0.0', max_digits=8, verbose_name='Estimated Cost')),
                ('actual_cost', models.DecimalField(decimal_places=2, default='0.0', max_digits=8, verbose_name='Actual Cost')),
                ('work_order_date', models.DateTimeField(blank=True, verbose_name='Submitted Date')),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.apartment', verbose_name='Apartment Number')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Work Order Submitted By')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30, verbose_name='Item Name')),
                ('item_cost', models.DecimalField(decimal_places=2, default='0.0', max_digits=8, verbose_name='Cost')),
                ('item_quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('work_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_order.workorder', verbose_name='Associated Work Order')),
            ],
        ),
    ]
