# Generated by Django 3.2.8 on 2021-10-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='apartment_id',
            new_name='apartment',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='workorderitem',
            old_name='work_order_id',
            new_name='work_order',
        ),
    ]
