# Generated by Django 3.2.8 on 2021-11-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0002_auto_20211025_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='current_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='Open', max_length=25, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='severity_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('EMERGENCY', 'Emergency')], default='Low', max_length=9, verbose_name='Severity'),
        ),
    ]
