# Generated by Django 3.2.8 on 2021-11-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0003_auto_20211113_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='actual_completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Completion Date'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='desired_completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desired Completion Date'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_order_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submitted Date'),
        ),
    ]
