# Generated by Django 3.2.8 on 2021-10-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(default='', max_length=30, verbose_name='Property Name')),
                ('street_address', models.CharField(default='', max_length=40, verbose_name='Street Address')),
                ('city', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='NE', max_length=2)),
                ('zipcode', models.CharField(default='00000', max_length=9, verbose_name='Zip Code')),
                ('age_in_years', models.CharField(blank=True, default='', max_length=2, verbose_name='Age (In Years)')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt_num', models.CharField(default='', max_length=5, verbose_name='Apartment Number')),
                ('size_in_sqft', models.IntegerField(default=0, verbose_name='Size (sqft)')),
                ('number_of_bedrooms', models.IntegerField(default=0, verbose_name='Number of Bedrooms')),
                ('description', models.CharField(default='', max_length=300)),
                ('client_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='client.client', verbose_name='Resident')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property', verbose_name='Property')),
            ],
        ),
    ]
