# Generated by Django 3.2.8 on 2021-10-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='property_id',
            new_name='property',
        ),
    ]
